### PR TITLE
Section 5 Development

### PR DESCRIPTION
**Pull request by rwstanfo**
Clean up of Section 5 Aerodynamics is complete.  Still needs a thorough update, particularly with formatting and consistency of how/where things are defined.  The figure of the boundary layer in Subsection 5.4 lost some of the extra labels when it was converted to SVG.  Various other notes and comments were left in the source code for future revisions.

### CODE REVIEW

**Comment by cooknl** [comment]
I'll look at it today!

**Comment by rwstanfo** [comment]
Sounds good.  I've re-titled this pull request to be more descriptive.  Last night I didn't realize that it used my branch name as the default name for the pull request.  But hopefully everything works as intended.  

I intentionally tried a new branching strategy on my fork to see what would happen.  I forked the master, made a dev branch, then am making feature branches off of that for each chapter.  I merged my Section 05 feature branch into my dev last night and that's what this pull request is based off of.

**Comment by cooknl** [comment]
I'm curious. Are you merging the original master back in to your fork
master and dev branches prior to creating a pull request?

This allows for a lower risk of merge conflicts during the pull request.

**Comment by rwstanfo** [comment]
Yes, sort of.  I rebaselined my forked dev branch to the original master, then merged in my Section 5 feature branch to dev. I created a pull request from my dev branch.

**Comment by cooknl** [comment]
Sorry for the delay. It's been a bit weird, as we all know.

I plan on checking these out tonight.

**Pull request merged**
