### PR TITLE
Subsection 2.6.1 of Section 2.6 Statistics

### PR DESCRIPTION
**Pull request by flighttestfact**

### CODE REVIEW

**Comment by cooknl** [comment]
What's the difference between \[ \] and $ $??

**Comment by flighttestfact** [comment]
Inline math via $$
Display modemath via \[ and \].
Inline math is restricted in height. Own line math is not.
https://www.overleaf.com/learn/latex/Mathematical_expressions#Reference_guide
https://tex.stackexchange.com/questions/410863/what-are-the-differences-between-and

**Comment by cooknl** [comment]
Ah! I've been using `$$ $$` for 2 years without knowing better. I'll go back and change `$$  $$` to `\[ \]`

Perhaps we should use `\( \)` for inline, as well? 
<https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode>

In other news, I've started a wiki page for a Style Guide to help with questions like this:
<https://github.com/Society-of-Flight-Test-Engineers/handbook-2013/wiki/Handbook-Markdown-Style-Guide>

**Comment by flighttestfact** [comment]
Thumbs up emoji.  Glad to add one small bit of knowledge to this project.  

I am open to input and your leadership decisions on style.

**Comment by cooknl** [comment]
`\[ \]` and `\( \)` it is, then! I'll include the changes for the sections already complete.

**Pull request merged**
