### PR TITLE
Section 7 cooknl

### LINKED ISSUE #106: 07.03 Vertical Center of Gravity Measurement

### LINKED ISSUE #107: 07.04 Moment & Product of Inertia Measurement

### PR DESCRIPTION
**Pull request by cooknl**
Hey, all. If you have a few minutes, I'd be interested in seeing your thoughts on Section 7 "Mass Properties".

This closes #106 and closes #107

### CODE REVIEW

**Comment by flighttestfact** [comment]
definition for "allowable cb" has the word "determined" broken on two lines.

**Comment by flighttestfact** [comment]
The figure about 7.4.1 interferes with the text.

**Comment by flighttestfact** [comment]
I'm guessing 7.4.1 is about where you stopped, so I'll stop reviewing for now?

**Comment by cooknl** [comment]
I went through the whole thing...

**Comment by flighttestfact** [comment]
Heading 7.4 does not appear in the sidebar. Formatted with different size font.

**Comment by flighttestfact** [comment]
Steps 4 and 6 of 7.3 formatting has line wraps in weird places.

**Comment by flighttestfact** [comment]
Formatting of units in 7.4.1 seems off.

**Comment by flighttestfact** [comment]
Aircraft moment of inertia summary:
I_zb is not in math mode or coded incorrectly. Same with subsequent values of inertia moments.

**Comment by cooknl** [comment]
Hmm.... I'll check that out

**Comment by cooknl** [comment]
> definition for "allowable cb" has the word "determined" broken on two lines.

Fixed

**Comment by cooknl** [comment]
> I'm guessing 7.4.1 is about where you stopped, so I'll stop reviewing for now?

image

I don't think we're seeing the same things...

How are you viewing this? 

I think you may be looking at the "master" branch, not the "Section-7-cooknl" branch.

I'll go ahead and merge the pull request, then you can still review and we'll fix things there....

**Pull request merged**
